-- Create a new database and schemas for streaming data processing
CREATE DATABASE IF NOT EXISTS STREAMING_DB;
USE DATABASE STREAMING_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS PROCESSED;