name: CI    

on:    # when to run the workflow (e.g., on push or pull request)
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:   # define jobs to run in the workflow
  test:     # job name
    runs-on: ubuntu-latest  # specify the OS to run the job on

    steps:  # steps to execute in the job
    - name: Checkout code
      uses: actions/checkout@v4 # checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # set up the Python environment
      with:
        python-version: '3.13.5'    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pip install -r stream_simulator/requirements.txt

    - name: Run pytest
      run: pytest tests/    # run the tests using pytest
